# Generated by Django 3.1.4 on 2020-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.FloatField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Adj_Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
    ]
