# Generated by Django 3.1.4 on 2020-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TickerTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastRun', models.DateField(verbose_name='DateLastRun')),
            ],
        ),
    ]
